#Experiment No. 8
##Tools for EDA - Study of Numpy
#### Ayush Phale PRN-25070123028
###### ENTC A2


In [ ]:
#why numpy
#Faster than lisys
#Used for numerical computation
#Base for pandas

In [ ]:
#Declaration of numpy
import numpy as np

a = np.array ([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)


[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
##Dimension of Array
print(a.ndim)
print(b.ndim)


1
2


In [ ]:
#Shape of Arrays
print(a.shape)
print(b.shape)

(4,)
(2, 3)


In [ ]:
#Data types of Arrays
print(a.dtype)
print(b.dtype)


int64
int64


In [ ]:
#Matrix Multiplication
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.zeros((3,3)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1,10,2))



[1 3 5 7 9]


In [ ]:
print(np.linspace(0,1,5))


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
c= a*2
d=a+5
print(c)
print(d)


[20 40 60 80]
[15 25 35 45]


In [ ]:
a+5

array([15, 25, 35, 45])

In [ ]:
#Average
print(np.mean(a)) #With print command we get direct answer


25.0


In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.max(a)

np.int64(40)

In [ ]:
np.min(a)

np.int64(10)